name: publish-on-tag

on:
  push:
    tags:
      - 'chrome-devtools-mcp-v*'
  workflow_dispatch:

permissions:
  id-token: write # Required for provenance attestation
  contents: read

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build and bundle
        run: npm run bundle
        env:
          NODE_ENV: 'production'

      - name: Publish @secforge/chrome-devtools-mcp
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
